### ISSUE TITLE
dbGap数据申请及下载全过程

### ISSUE THREAD

**Issue by JiFansen** [JiFansen/Blog#37]
## **dbGap的这个数据总体来说是费了相当多的时间和精力去申请和下载的，那么现在我就简单总结一下整个过程。**  

1.  NCBI上有很多组学的数据，其实总体上我对这个数据库了解得不多，用得也不是很多。但是我们知道这些数据有很大一部分是公开的，随时都可以下载。但是也有一些比较特殊的project，它们的数据是相对封闭的，如果使用的话就需要申请。那么我们使用到的这批数据就是这样需要申请的。

2. 之前也经历过一些数据申请的工作，总体来说是非常繁琐的。我们作为外国人去申请美国的数据要提交很多研究计划之类的东西，还需要国内的行政机关单位一步一步去审批。之前我一直都没有申请成功，这一次好在蓝老师帮助我们，我们才会敢去申请，如果老板啥也不说，我们肯定不会主动去申请的。

3. 在之前，我们看了一些文章然后根据我们自己的研究问题以及实际需求，锁定了几个数据源。然后我把这个表发给了蓝老师。因为我们对这些数据申请上没什么经验，所以这事也就这么过去了。几天后，蓝老师给我发来邮件，告诉我按照这个链接去申请，又告诉我他已经重新申请成功了eRA的账号。有了这些东西我就有资格去写申请材料了。我意味申请材料会是那种长篇大论的文书，没想到这次申请的dbGAP的数据只需要写不到1000字的东西，所以我就一步一步申请了。

4. 这个dbGAP数据申请，写好文书之后它们不会立即审核，而是先打到我们学校的科技处部门，让科技处部门先审核一遍。这方面我觉得也可以理解，做得很专业到位。而且，我们自己的学校科技处一般不会拒绝我们数据的申请，都是直接过了。所以，在学校科技处这一关，并没有想象中的那么复杂。

5. 但是，问题来了。我在申请数据的时候，遇到过要填写比如说PI信息、数据安全保障人员的信息等内容。PI信息我就按照老板的信息去写的，而数据保障主管我是随便写的，这一点我确实做得不好，没有重视数据保密安全。因此，第一次申请就这样被拒绝了。

6. 吸取上次的教训，我这次把数据安全主管写成了杨涛老师，又重新申请了一次。但是，这一次又说PI信息提供不完整。它们那边总是一次说一个问题，反反复复。那这一次我已经没有办法了，老板信息就是我填写的这样。于是我们几次求助于科技处，希望科技处当面和他们沟通。在这个过程中，可能科技处和那边的问题，中途又拒绝了我们两次。

7. 再之后，我们又遇到了比如说研究计划不明确，申请数据不能与其他数据集结合用于研究等问题，我们都一一改过来了。终于，再不久前我们成功拿到了数据下载的资格。

8. 谁也不会想到，我们拿到了数据下载的资格以后竟然遇到了不会下载数据的尴尬问题。我之前下载数据都是直接wget这样非常简单的方式，但是这一次不一样，数据量一大就需要用单独的下载方法。NCBI用了aspera connect的方法。一开始我就被这个东西搞晕了。我自己大概有一个印象是它类似于迅雷的作用，但是怎么用呢？用什么版本呢？windows还是linux?以及我们的数据本身是那种不对外开放的数据，这种数据下载和一般的数据下载有什么不同？这些问题就足足折磨了我一整天，整个过程非常凌乱和痛苦。

9. 我在windows上前前后后安装这个aspera connect软件安了四五遍，以为安上了，又不知道怎么用。最后好不容易知道了，其实这个软件是自动会安装一个web版的插件，所以找到我们要下载的数据，直接就可以往本地传，速度非常快。由于数据量比较大，直接往本地传电脑可能会崩，所以我又拿出来我的硬盘，尝试往硬盘里面传，最后终于能够把数据下载下来了。
10. 这个时候，最坑的事情发生了。我下载下来的数据是一个加密的数据。也就是说，下载了3G的数据最后一个都看不了。在之前的说明里面我知道数据需要解密，但是怎么解还不是特别清楚。所以，我又看了解密方法以及拿出来一个测试文件尝试解密。然而，爆出来一堆错误都不知道怎么解决。明明可以的啊，为什么不行？最后，看到已经晚上十点半了，实在没办法，把几个网页保存下来，关机回家。

11. 第二天，我又重新拾起来昨天的没有整明白的事情，慢下来仔仔细细去研究。奇迹发生了，在我不超过一个上午的时间，我竟然奇迹般地把昨天的问题解决了。这过程是不是跨度有点大？那么就然我慢慢给大家讲解我是怎么做的吧！！！

**Comment by JiFansen** [comment]
- 首次，下载安装aspera connect。下载地址：https://downloads.asperasoft.com/en/downloads/8?list  
```
wget https://download.asperasoft.com/download/sw/connect/3.8.0/ibm-aspera-connect-3.8.0.158555-linux-g2.12-64.tar.gz
tar zxf ibm-aspera-connect-3.8.0.158555-linux-g2.12-64.tar.gz
sh ibm-aspera-connect-3.8.0.158555-linux-g2.12-64.sh
echo 'PATH=$PATH:~/.aspera/connect/bin/' >> ~/.bashrc
source ~/.bashrc
ascp --help
```

- 下载SRA Toolkit。这一部分在我另一篇笔记https://github.com/JiFansen/Blog/issues/35
中有很多个链接，相对简单，这里不再赘述。

- 之后，登录dbGAP，找到你要下载并且申请通过的数据条目。登陆网址：https://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?filter=wlid&page=downloads&wlid=18440&login=NFL

- # _之后是非常关键的一步，我在之前的尝试中失败以及下载数据到硬盘之后解密不成功都与这一步紧密相关。我们要设置保密数据下载的位置以及下载密钥。密钥的下载地址就在我之前提到的登录dbGAP之后就可以看到。数据下载的具体文件夹要是空的。这一点也很重要。但是具体密钥怎么加载以及数据下载位置的设置需要参考这篇：https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=dbgap_use讲解得很详尽。这非常重要。_

- 设置好了下载路径之后点击登录页面右边的download, 进入新页面。

- 我们利用第二种方式，commond line下载。按照下面的说明与提示进行ascp路径的相应替换就可以将genotype以及Phenotype下载下来。

- 下载下载的数据都是加密的，所以之前安装的SRA Toolkit里面的解密程序就派上用场，具体也参阅我上面提供的链接。

- 那我们还想要下载测序数据，这时候就需要选择https://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?page=request_details_pi&filter=rmode&rmode=sra&arid=251518&filter=arid这个链接里面（也就是My Request选项）的SRA Data，然后选择Run Selector，之后就是这个这个project里面所有病人的测序数据了，有WGS,WES,RNA-SEQ这些。

- 根据这个Run Selector的帮助文档：https://trace.ncbi.nlm.nih.gov/Traces/study/?go=help_prj 我选择出了RNA-seq的数据，然后下载了cart文件。这个文件就要放在我们之前设置下载目录的那个文件夹里面。具体的，总结起来就是密钥文件位置随意、起始设置数据下载文件夹要为空以及用cart文件下载数据时cart文件要在刚才说到的那个文件夹里面。之后借助SRA prefecth小工具就可以下载测序数据。

## 说了这么多，无非就是想总结一下，整个过程下来怎么做的便于以后用。我觉得还是要认真看每一个manual或者帮助文档。在我们没有一点头绪和方法的时候这是一个策略，虽然东西很多很杂，但是还是要认认真真，耐住性子去看。我觉得要不是我第一天看了很多，第二天也不会这么顺利。还是要静下心来慢慢地认真做啊。之后的话可能要用这些测序数据我们自己去按照TCGA的pipeline分析去得到表达矩阵，因为这些数据里面没有给我们。一点一点来吧。

以上。

**Comment by hitdpc** [comment]
你好，请问如何拿到eRA的账号呢？这个步骤对我来说比较重要。还有一个问题，是必须先明确地说明要申请哪些数据并有完整的项目计划才可以申请到下载权限吗？要被这个数据库搞崩溃了

**Comment by YanSiyuanVicky** [comment]
您好，不好意思请教一下，按照帖子上发布的流程申请之后，NIH秒拒了，理由是无法证实PI和IT director的身份，具体如图，拜托SO老师发邮件argue了，可是一直没有回音，网站上request的状态也一直是rejected的状态，请问您碰到过么？请问是重新申请还是静待回音呢？
![image](https://user-images.githubusercontent.com/86824550/124239304-2504c880-db4c-11eb-94e7-0970ced44ccf.png)

**Comment by YanSiyuanVicky** [comment]
sorry，I reopen this issue.

**Comment by jingydz** [comment]
请问楼上拿到eRA账号了吗？我也是无法登录

**Comment by Dccx0812** [comment]
> 您您，不好意思，按照按照帖子的之后流程，Nih秒秒拒拒流程网站上request的状态也一直是rejected的状态，请问您点击到什么？请问是重新申请还是静候回复呢？ ![图像](https://user-images.githubusercontent.com/86824550/124239304-2504c880-db4c-11eb-94e7-0970ced44ccf.png)

铁子你好呀：）请问你遇到的SO和IT认证的问题后来解决了嘛？

**Comment by xiiao-b** [comment]
> 您好，不好意思请教一下，按照帖子上发布的流程申请之后，NIH秒拒了，理由是无法证实PI和IT director的身份，具体如图，拜托SO老师发邮件argue了，可是一直没有回音，网站上request的状态也一直是rejected的状态，请问您碰到过么？请问是重新申请还是静待回音呢？ ![image](https://user-images.githubusercontent.com/86824550/124239304-2504c880-db4c-11eb-94e7-0970ced44ccf.png)

您好，请问一下该如何查看被拒的具体原因呢？我这边只能看到一个被拒绝的消息
![image](https://github.com/JiFansen/Blog/assets/71080772/e737b257-94e2-41f0-ba30-0b86f5b7a6c7)

**Comment by LXueqing12** [comment]
> > 您好，不好意思请教一下，按照帖子上发布的流程申请之后，NIH秒拒了，理由是无法证实PI和IT director的身份，具体如图，拜托SO老师发邮件argue了，可是一直没有回音，网站上request的状态也一直是rejected的状态，请问您碰到过么？请问是重新申请还是静待回音呢？ ![image](https://user-images.githubusercontent.com/86824550/124239304-2504c880-db4c-11eb-94e7-0970ced44ccf.png)
> 
> 您好，请问一下该如何查看被拒的具体原因呢？我这边只能看到一个被拒绝的消息 ![image](https://private-user-images.githubusercontent.com/71080772/335461005-e737b257-94e2-41f0-ba30-0b86f5b7a6c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTkyMTUsIm5iZiI6MTcyODk1ODkxNSwicGF0aCI6Ii83MTA4MDc3Mi8zMzU0NjEwMDUtZTczN2IyNTctOTRlMi00MWYwLWJhMzAtMGI4NmY1YjdhNmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyMjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMThhMTcyYmJhMGUzMGQyMWIyNzY2YjUyMzdmOGNlNjQxMTBkYzQxYzAyNjdjNmU5NjI5OWQ3ZGM3ZGZkM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b9iQMsFGVu1JOzacz4LhboQqAE7WlfmIp8KHNhvEGxw)

同样被拒绝但不知道原因，请问您知道该怎么查看具体原因了吗？

**Comment by Colecolenut** [comment]
Follow this issue
